# Generated by Django 5.2.6 on 2025-09-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('developer', models.CharField(max_length=100)),
                ('main_actors', models.CharField(max_length=200)),
                ('release_year', models.PositiveIntegerField()),
            ],
        ),
    ]
